### ISSUE TITLE
Futures vs Meteor.wrapAsync

### ISSUE THREAD

**Issue by dbismut** [kadirahq/meteor-stripe-konnect#4]
Hey,

I'm just curious why you don't use `Meteor.wrapAsync` at [stripe.js#L42](https://github.com/kadirahq/meteor-stripe-konnect/blob/master/server/stripe.js#L42)?

```javascript
var method = self.api[resource][name];
self[resource][name] = Meteor.wrapAsync(method, context);
```

instead of

```javascript
var method = self.api[resource][name];
self[resource][name] = function() {
    var args = _.toArray(arguments);
    var f = new Future();
    args.push(function(err, res) {
        if(err) {
            // stripe uses some custom error type
            // and it's doesn't play well with 
            // Meteor's error reporting 
            // and that's why we are using this
            var error = new Error(err.message);
            error.raw = err.raw;
            f.throw(error);
          } else {
              f.return(res);
          }
      });
     method.apply(context, args);
     return f.wait();
};
```

EDIT: I mean I understand they do the same internally, but since there is a built-in function in Meteor I was wondering why you weren't using it.

**Comment by arunoda** [comment]
I think @mnmtanish is playing with how to do it without `wrapAsync`.
@mnmtanish  is it?

**Comment by dbismut** [comment]
Maybe that comment explains it all actually, sorry if that's the case :)
```
// stripe uses some custom error type
// and it's doesn't play well with 
// Meteor's error reporting 
// and that's why we are using this
```

**Comment by mnmtanish** [comment]
> Thank god I wrote that comment :)

I honestly don't remember why I didn't use wrapAsync. I think the error type must be the issue.
I'll check it again in a few days just to make sure.
