### ISSUE TITLE
How should I capture errors returned by Stripe?

### ISSUE THREAD

**Issue by oliverlloyd** [kadirahq/meteor-stripe-konnect#5]
Perhaps I'm missing something obvious here (very possible) but I can't seem to work out how to catch and handle error responses from Stripe.

Client:

    var update = {
      exp_month: $(this).find('#card_expires').val().substr(0, 2),
      exp_year: $(this).find('#card_expires').val().substr(5, 2),
    };

    Meteor.call('updateCard', update, function(err, response) {
      // ...
    });

Server:

    updateCard: function(update) {
      check(update, {
        exp_month: String,
        exp_year: String,
      });
      // Some stuff to get customer and card ids
      Stripe.updateCard(customer.id, cardId, update);
      // Update some other stuff... 
    },

    Stripe = {
      updateCard: function(customerId, cardId, update) {
        check(customerId, String);
        check(cardId, String);
        return stripe.customers.updateCard(customerId, cardId, update);
      },
    };

If I pass in an expiry year of `2099` I get this response from Stripe `Error: Your card's expiration year is invalid.` But the error is thrown before I can grab it so even if I try to check the response from the `stripe.customers.updateCard()` I can't access it because the error is already thrown and I end up with a sanitised `"Internal server error [500]"` error on the client.

**Comment by arunoda** [comment]
Use a try catch block in the server.

**Comment by oliverlloyd** [comment]
Yep, that was pretty obvious! Thanks for the quick response.

**Comment by oliverlloyd** [comment]
Hmm, okay, not quite so obvious. Before I start pulling this object apart, is there a sensible way to throw this error when the format of the response is: `{ [Error: Your card's expiration year is invalid.] stack: [Getter] }`?

I presume this is related to this:
```
          if(err) {
            // stripe uses some custom error type
            // and it's doesn't play well with 
            // Meteor's error reporting 
            // and that's why we are using this
            var error = new Error(err.message);
            error.raw = err.raw;
            f.throw(error);
          } else {
            f.return(res);
          }
```

**Comment by arunoda** [comment]
You mean you need to pass this info to the client. Okay grab the message
with err.raw and create a new Meteor.Error and throw.

It's not always good to send server errors to client, specially when there
are money involved. So have a look at to that as well.

**Comment by oliverlloyd** [comment]
err.raw, that did the trick! Thanks again.

And yes, we'll check the errors that the API sends and make sure we don't give anything away that shouldn't be disclosed.
